PhoneBookApplication/Models/PhoneBook.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace PhoneBookApplication.Models
{
    public class PhoneBook
    {

        [Key]
        [DisplayName("Phone id")]
        public int PhoneId { get; set; }
        [StringLength(15)]
        public string FirstName { get; set; }

        [StringLength(15)]
        public string LastName { get; set; }  
        [StringLength(15)]
        public string CompanyName { get; set; }

        [StringLength(35)]
        public string Email { get; set; }

        [StringLength(15)]
        public string ContactNumber { get; set; }
        public string FileName { get; set; }


    }
}

PhoneBookApplication/Controllers/PhoneBookController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PhoneBookApplication.Data;
using PhoneBookApplication.Models;
using PhoneBookApplication.Service.Contract;
using PhoneBookApplication.ViewModel;

namespace PhoneBookApplication.Controllers
{
    public class PhoneBookController : Controller
    {
        
        private IContactService _contactService;
        private const string alreadyExists = "Contact already exists.";
        private const string wentWrong = "Something went wrong, try again later";
        private const string savedSuccess = "Contact saved successfully.";
        private const string deleteSuccess = "Contact deleted successfully.";
        private const string updateSuccess = "Contact updated successfully.";
        public PhoneBookController(IContactService contactService)
        {
            _contactService = contactService;
          
         
            
        }

        public IActionResult Index(char? character,int page = 1,int pageSize = 2 )
        {


         
           
           
            // Get total count of categories
            var totalCount = _contactService.GetAll().Count();

            // Calculate total number of pages
            var totalPages = (int)Math.Ceiling((double)totalCount / pageSize);

            var contacts = character == null ? _contactService.GetPaginatedPhoneBooks(page, pageSize) : _contactService.GetPaginatedPhoneBooksWithCharacter(character, page, pageSize);
          
            ViewBag.TotalPages = totalPages;
            ViewBag.CurrentPage = page; // Pass the current page number to the ViewBag
            ViewBag.PageSize = pageSize;
            ViewBag.Character = character;
            return View(contacts);
        }
        public IActionResult Details(int id)
        {
            var contact = _contactService.GetContact(id);
            if (contact == null)
            {
                return NotFound();
            }
            return  View(contact);
        }
        [HttpGet]
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult Create(PhoneBookViewModel contactViewModel)

        {
            if (ModelState.IsValid)
            {
                var contact = new PhoneBook()
                {
                    FirstName = contactViewModel.FirstName,
                    LastName = contactViewModel.LastName,
                    CompanyName = contactViewModel.CompanyName,
                    Email = contactViewModel.Email,
                    ContactNumber = contactViewModel.ContactNumber,
                   
                };
                var result = _contactService.AddContact(contact,contactViewModel.File);
                if(result== alreadyExists ||  result== wentWrong)
                {
                    TempData["ErrorMessage"] = result;
                }
                else if(result== savedSuccess)
                {
                    TempData["SuccessMessage"] = result;
                    return RedirectToAction("Index");
                }
            }
            return View(contactViewModel);

        }
        [HttpGet]
        [Authorize]
        public IActionResult Edit(int id)
        {
            var contact = _contactService.GetContact(id);
            if (contact == null)
            {
                return NotFound();

            }
            return View(contact);
        }
        [HttpPost]
        [Authorize]
        public IActionResult Edit(PhoneBook contact)
        {
            if (ModelState.IsValid)
            {
                var result = _contactService.EditContact(contact);
                if(result==wentWrong || result == alreadyExists)
                {
                    TempData["ErrorMessage"] = result;
                }
                else
                {
                    TempData["SuccessMessage"] = result;
                    return RedirectToAction("Index");
                }
            }
            return View(contact);
        }
        [Authorize]
        public IActionResult Delete(int id)
        {
            var contact = _contactService.GetContact(id);
            if (contact == null)
            {
                return NotFound();

            }
            else
            {

                return View(contact);

            }
        }
        [Authorize]
        [HttpPost]
        public IActionResult DeleteConfirm(int PhoneId)
        {
            var result = _contactService.RemoveContact(PhoneId);
            if (result == deleteSuccess)
            {
                TempData["SuccessMessage"] = result;
            }
            else
            {
                TempData["ErrorMessage"] = result;  
            }
            return RedirectToAction("Index");



        }
      
    }
}

PhoneBookApplication/Views/PhoneBook/Create.cshtml
@using PhoneBookApplication.ViewModel
@model PhoneBookViewModel
<h1>Add New Contact</h1>
<form asp-action="Create" method="post" enctype="multipart/form-data">

    <div class="form-group">
        <label asp-for="FirstName" class="control-label">First name</label>
        <input asp-for="FirstName" class="form-control" />
        <span asp-validation-for="FirstName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="LastName" class="control-label">Last name</label>
        <input asp-for="LastName" class="form-control" />
        <span asp-validation-for="LastName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="CompanyName" class="control-label">Company name</label>
        <input asp-for="CompanyName" class="form-control" />
        <span asp-validation-for="CompanyName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ContactNumber" class="control-label">Contact number</label>
        <input asp-for="ContactNumber" class="form-control" />
        <span asp-validation-for="ContactNumber" class="text-danger"></span>
    </div> 
    <div class="form-group">
        <label asp-for="Email" class="control-label">Email address</label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="form-group mb-2">
        <label asp-for="File" class="control-label"></label>
        <input asp-for="File" type="file" class="form-control" />
        <span asp-validation-for="File" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Submit" class="btn btn-primary" />
        <a asp-action="Index" class="btn btn-default">Cancel</a>
    </div>
    
</form>

PhoneBookApplication/Views/PhoneBook/Delete.cshtml
@model PhoneBook
<h1>Delete Contact</h1>
<div>
    <h4> Are you sure you want to delete this Contact?</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2"> FirstName:</dt>
        <dt class="col-sm-10">@Model.FirstName</dt>

        <dt class="col-sm-2"> LastName:</dt>
        <dt class="col-sm-10">@Model.LastName</dt>

        <dt class="col-sm-2"> Company:</dt>
        <dt class="col-sm-10">@Model.CompanyName</dt>

        <dt class="col-sm-2"> Contact Number:</dt>
        <dt class="col-sm-10">@Model.ContactNumber</dt>

        <dt class="col-sm-2"> Email:</dt>
        <dt class="col-sm-10">@Model.Email</dt>
    </dl>

    <form asp-action="DeleteConfirm" method="post">
        <input type="hidden" asp-for="@Model.PhoneId" />
        <div class="form-group">
            <input type="submit" class="btn btn-danger" value="delete" />
            <a asp-action="Index" class="btn btn-primary"> Back to List </a>

        </div>
    </form>
</div>

PhoneBookApplication/Views/PhoneBook/Details.cshtml
@model PhoneBook
<h2>Contact Details</h2>
<div>
  
    <h4>First name : @Model.FirstName</h4>
    <h4>Last name : @Model.LastName</h4>
    <h4>Comapany name : @Model.CompanyName</h4>
    <h4>Contact number : @Model.ContactNumber</h4>
    <h4>Email : @Model.Email</h4>
</div>
<div>
    <button type="button" class="btn btn-primary" onclick="window.location.href='@Url.Action("Index", "PhoneBook")'">Go Back</button>

    
    <a asp-action="Edit" asp-route-id="@Model.PhoneId" class="btn btn-warning">Modify</a>
    <a asp-action="Delete" asp-route-id="@Model.PhoneId" class = "btn btn-danger">Delete</a>
</div>

PhoneBookApplication/Views/PhoneBook/Edit.cshtml
@model PhoneBook
<h1>Modify Contact</h1>
<form asp-action="Edit">
    <input type="hidden" asp-for="PhoneId" />
    <div class="form-group">
        <label asp-for="FirstName" class="control-label"></label>
        <input asp-for="FirstName" class="form-control" />
        <span asp-validation-for="FirstName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="LastName" class="control-label"></label>
        <input asp-for="LastName" class="form-control" />
        <span asp-validation-for="LastName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="CompanyName" class="control-label"></label>
        <input asp-for="CompanyName" class="form-control" />
        <span asp-validation-for="CompanyName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Email" class="control-label"></label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ContactNumber" class="control-label"></label>
        <input asp-for="ContactNumber" class="form-control" />
        <span asp-validation-for="ContactNumber" class="text-danger"></span>
    </div>
    <input type="submit" class="btn btn-primary" value="Save" />

</form>

PhoneBookApplication/Views/PhoneBook/Index.cshtml
@model List<PhoneBook>
<form method="get">
    <div>
        <button class="btn btn-secondary" type="submit" value="">All</button>
        @for (var character = 'A'; character <= 'Z'; character++)
        {
            <button class="btn btn-outline-secondary" type="submit" name="character" value="@character">@character</button>
        }
    </div>
</form>
@if (ViewBag.Character == null)
{
    <h1>Contact List</h1>
}
else
{
    <h1>Contact List : @ViewBag.Character</h1>
}


<a asp-action="Create" class="btn btn-success   ">Add</a>
@if (Model == null || Model.Count == 0)
{
    <div class="container d-flex justify-content-center align-items-center" style="height: 50vh;">
        <div id="recordNotFound" class="text-center">
            <img src="~/images/recordnotfound.jpg" class="mb-3" alt="Record Not Found">
            <h2 class="display-5 noRecords">No records to display ...</h2>
        </div>
    </div>

}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>Contact</th>
                <th>Contact Id</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var contact in Model)
            {
                <tr>
                  
                    <td>

                        <img src="@Url.Content("~/Uploads/"+@contact.FileName)" alt="Category Image" width="50" height="50" />

                    </td>
                   
                    <td>@contact.PhoneId</td>
                    <td>@contact.FirstName</td>
                    <td>@contact.LastName</td>
                    <td>
                        <a asp-action="Details" asp-route-id="@contact.PhoneId" class="btn btn-primary">View Details</a>


                    </td>

                </tr>
            }

        </tbody>
    </table>
}
<!-- Pagination -->
@* @if (Model.Count>0 )
{ *@
<div id="pagination">
    <!-- Page size dropdown -->
    <label for="pageSize">Page Size:</label>
    <select id="pageSize" onchange="changePageSize(this)">
        <option value="2">2</option>
        <option value="4">4</option>
        <option value="6">6</option>
        <!-- Add more options as needed -->
    </select>
    <ul class="pagination">
        @for (int i = 1; i <= ViewBag.TotalPages; i++)
        {
            <li class="page-item @(i == ViewBag.CurrentPage ? "active" : "")">
                <a class="page-link" href="/PhoneBook/Index?page=@i&pageSize=@ViewBag.PageSize">@i</a>
            </li>
        }
    </ul>
</div>
@* } *@

@* <div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row">
            <div class="col-sm-6">

                <div class="list list-row block">
                    <div class="list-item" data-id="19">
                        <div><a href="#" data-abc="true"><span class="w-48 avatar gd-warning">S</span></a></div>
                        <div class="flex">
                            <a href="#" class="item-author text-color" data-abc="true">Sam Kuran</a>
                            <div class="item-except text-muted text-sm h-1x">For what reason would it be advisable for me to think about business content?</div>
                        </div>
                        <div class="no-wrap">
                            <div class="item-date text-muted text-sm d-none d-md-block">13/12 18</div>
                        </div>
                    </div>
                    <div class="list-item" data-id="7">
                        <div><a href="#" data-abc="true"><span class="w-48 avatar gd-primary"><img src="https://img.icons8.com/color/48/000000/administrator-male.png" alt="."></span></a></div>
                        <div class="flex">
                            <a href="#" class="item-author text-color" data-abc="true">Kinley Adolf</a>
                            <div class="item-except text-muted text-sm h-1x">For what reason would it be advisable for me to think about business content?</div>
                        </div>
                        <div class="no-wrap">
                            <div class="item-date text-muted text-sm d-none d-md-block">21 July</div>
                        </div>
                    </div>
                    <div class="list-item" data-id="17">
                        <div><a href="#" data-abc="true"><span class="w-48 avatar gd-warning">H</span></a></div>
                        <div class="flex">
                            <a href="#" class="item-author text-color" data-abc="true">Velden Kamut</a>
                            <div class="item-except text-muted text-sm h-1x">For what reason would it be advisable for me to think about business content?</div>
                        </div>
                        <div class="no-wrap">
                            <div class="item-date text-muted text-sm d-none d-md-block">13/3/19</div>
                        </div>
                    </div>
                    <div class="list-item" data-id="16">
                        <div><a href="#" data-abc="true"><span class="w-48 avatar gd-info">F</span></a></div>
                        <div class="flex">
                            <a href="#" class="item-author text-color" data-abc="true">Stuart Kim</a>
                            <div class="item-except text-muted text-sm h-1x">For what reason would it be advisable for me to think about business content?</div>
                        </div>
                        <div class="no-wrap">
                            <div class="item-date text-muted text-sm d-none d-md-block">03/1/19</div>
                        </div>
                    </div>
                    <div class="list-item" data-id="4">
                        <div><a href="#" data-abc="true"><span class="w-48 avatar gd-success"><img src="https://img.icons8.com/color/48/000000/guest-male.png" alt="."></span></a></div>
                        <div class="flex">
                            <a href="#" class="item-author text-color" data-abc="true">Simply Fry</a>
                            <div class="item-except text-muted text-sm h-1x">For what reason would it be advisable for me to think about business content?</div>
                        </div>
                        <div class="no-wrap">
                            <div class="item-date text-muted text-sm d-none d-md-block">2 hours ago</div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
 *@
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>



@if (Model == null || !Model.Any())
{
    <script>
        $(document).ready(function () {
            NotFoundImage();
        });

        function NotFoundImage() {
          
            $('#recordNotFound').show();
            $('#pagination').hide();
        }

                


    </script>

}
<script>
    document.addEventListener("DOMContentLoaded", function () {
        var currentPageSize = @ViewBag.PageSize; // Get current page size from ViewBag
        var pageSizeDropdown = document.getElementById("pageSize");
        // Set selected option based on current page size
        for (var i = 0; i < pageSizeDropdown.options.length; i++) {
            if (pageSizeDropdown.options[i].value === currentPageSize.toString()) {
                pageSizeDropdown.selectedIndex = i;
                break;
            }
        }
    });

    function changePageSize(select) {
        var pageSize = select.value;
        var currentPage = @ViewBag.CurrentPage;
        var character = "@ViewBag.Character";
        window.location.href = "/PhoneBook/Index?page=" + currentPage + "&pageSize=" + pageSize+"&character="+character;
    }


      
   

</script>

@* css file*@
<link href="~/css/phonebookindex.css" rel="stylesheet" />